config/routes.rb
Rails.application.routes.draw do
  get "product_index/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get 'webpay-plus/refresh_respond_data_json', to: 'webpay_plus#refresh_respond_data_json', as: :refresh_webpay_plus_json
  get '"webpay-mall/refresh_respond_data_json', to: 'webpay_plus_mall#refresh_respond_data_json', as: :refresh_webpay_mall_json
  get 'webpay-plus-diferido/refresh_respond_data_json', to: 'webpay_plus_deferred#refresh_respond_data_json', as: :refresh_webpay_plus_deferred_json
  get 'webpay-mall-diferido/refresh_respond_data_json', to: 'webpay_plus_mall_deferred#refresh_respond_data_json', as: :refresh_webpay_mall_deferred_json
  root to: "product_index#index"

  get "/oneclick-mall", to: "home#oneclick_mall", as: :oneclick_mall
  get "/transaccion-completa", to: "home#transaccion_completa", as: :transaccion_completa
  get "/patpass-comercio", to: "home#patpass_comercio", as: :patpass_comercio

  # --- API Reference ---
  get "/api-reference/webpay-plus", to: "webpay_plus#show_operations", as: :webpay_plus_api_operations
  get "/api-reference/webpay-mall", to: "webpay_plus_mall#show_operations", as: :webpay_mall_api_operations
  get "/api-reference/webpay-plus-diferido", to: "webpay_plus_deferred#show_operations", as: :webpay_deferred_api_operations
  get "/api-reference/webpay-mall-diferido", to: "webpay_plus_mall_deferred#show_operations", as: :webpay_mall_deferred_api_operations

  # --- Webpay Plus ---
  # Controladores: WebpayPlusController
  get "webpay-plus/create", to: "webpay_plus#create", as: :webpay_plus_create
  match "webpay-plus/commit", to: "webpay_plus#commit", via: [ :get, :post ], as: :webpay_plus_commit
  get "webpay-plus/refund", to: "webpay_plus#refund", as: :webpay_plus_refund
  get "webpay-plus/status", to: "webpay_plus#status", as: :webpay_plus_status

  # --- Webpay Plus Mall ---
  # Controladores: WebpayPlusMallController
  get "webpay-mall/create", to: "webpay_plus_mall#create", as: :webpay_mall_create
  match "webpay-mall/commit", to: "webpay_plus_mall#commit", via: [ :get, :post ], as: :webpay_mall_commit
  get "webpay-mall/refund", to: "webpay_plus_mall#refund", as: :webpay_mall_refund
  get "webpay-mall/status", to: "webpay_plus_mall#status", as: :webpay_mall_status

  # --- Webpay Plus Diferido ---
  # Controladores: WebpayPlusDeferredController
  get "webpay-plus-diferido/create", to: "webpay_plus_deferred#create", as: :webpay_deferred_create
  match "webpay-plus-diferido/commit", to: "webpay_plus_deferred#commit", via: [ :get, :post ], as: :webpay_deferred_commit
  get "webpay-plus-diferido/capture", to: "webpay_plus_deferred#capture", as: :webpay_deferred_capture
  get "webpay-plus-diferido/refund", to: "webpay_plus_deferred#refund", as: :webpay_deferred_refund
  get "webpay-plus-diferido/status", to: "webpay_plus_deferred#status", as: :webpay_deferred_status

  # --- Webpay Plus Mall Diferido ---
  # Controladores: WebpayPlusMallDeferredController
  get "webpay-mall-diferido/create", to: "webpay_plus_mall_deferred#create", as: :webpay_mall_deferred_create
  match "webpay-mall-diferido/commit", to: "webpay_plus_mall_deferred#commit", via: [ :get, :post ], as: :webpay_mall_deferred_commit
  get "webpay-mall-diferido/capture", to: "webpay_plus_mall_deferred#capture", as: :webpay_mall_deferred_capture
  get "webpay-mall-diferido/refund", to: "webpay_plus_mall_deferred#refund", as: :webpay_mall_deferred_refund
  get "webpay-mall-diferido/status", to: "webpay_plus_mall_deferred#status", as: :webpay_mall_deferred_status

  # --- Oneclick Mall ---
  # Controladores: OneclickMallController
  get "oneclick-mall/start", to: "oneclick_mall#start", as: :oneclick_mall_start 
  get "oneclick-mall/finish", to: "oneclick_mall#finish", as: :oneclick_mall_finish
  get "oneclick-mall/authorize", to: "oneclick_mall#authorize", as: :oneclick_mall_authorize
  get "oneclick-mall/delete", to: "oneclick_mall#delete", as: :oneclick_mall_delete
  get "oneclick-mall/refund", to: "oneclick_mall#refund", as: :oneclick_mall_refund
  get "oneclick-mall/status", to: "oneclick_mall#status", as: :oneclick_mall_status

  # --- Oneclick Mall Diferido ---
  # Controladores: OneclickMallDeferredController
  get "oneclick-mall-diferido/start", to: "oneclick_mall_deferred#start", as: :oneclick_mall_deferred_start
  get "oneclick-mall-diferido/finish", to: "oneclick_mall_deferred#finish", as: :oneclick_mall_deferred_finish
  get "oneclick-mall-diferido/authorize", to: "oneclick_mall_deferred#authorize", as: :oneclick_mall_deferred_authorize
  get "oneclick-mall-diferido/delete", to: "oneclick_mall_deferred#delete", as: :oneclick_mall_deferred_delete
  get "oneclick-mall-diferido/status", to: "oneclick_mall_deferred#status", as: :oneclick_mall_deferred_status
  get "oneclick-mall-diferido/refund", to: "oneclick_mall_deferred#refund", as: :oneclick_mall_deferred_refund
  get "oneclick-mall-diferido/capture", to: "oneclick_mall_deferred#capture", as: :oneclick_mall_deferred_capture
end

app/views/partials/_channels.html.erb
<div class="contact-container">
    <div class="questions-container">
        <span class="header">¿Tienes alguna duda de integración?</span>
        <div class="list">
            <div class="question-item">
                <span class="title">Escríbenos por slack</span>
                <div class="inner-container">
                    <a href="https://invitacion-slack.transbankdevelopers.cl/slack_community" target="_blank" rel="noopener">
                        <%= image_tag "slack.png", alt: "slack", width: "124", height: "32" %>
                    </a>
                    <span class="container">Únete a nuestra comunidad de integradores. Nuestro equipo está ahí para
                        ayudarte</span>
                </div>
            </div>

            <div class="question-item">
                <span class="title">Envíanos un mensaje</span>
                <div class="inner-container">
                    <a href="mailto:soporte@transbank.cl" target="_blank" rel="noopener">
                        <%= image_tag "outlook.png", alt: "outlook", width: "32", height: "32" %>
                    </a>
                    <span class="container">Necesitas resolver algún tipo de incidencia, contáctanos a través de correo
                        electrónico</span>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/partials/_footer.html.erb
<footer class="bg-tbk-black-bg tbk-footer">
    <div class="footer-item">
      <%= image_tag "tbk-white.svg", alt: "tbk logo white" %>
    </div>
    <span class="footer-item boder-t-gray3">
        Hecho con amor por Continuum y Transbank.
    </span>
</footer>

app/views/partials/_header.html.erb
<div class="tbk-header" data-controller="menu">
    <div class="tbk-header-left">
        <button class="tbk-buger-menu" id="burger-menu" data-action="menu#toggleMenu">
            <%= image_tag "menu.svg", alt: "tbk logo", width: "32", height: "32" %>
        </button>
        <a href="<%= root_path %>">
            <%= image_tag "tbk-logo.svg", alt: "tbk logo", width: "181", height: "34", class: "tbk-logo" %>
        </a>
    </div>
    <div class="tbk-header-options">
        <a href="https://invitacion-slack.transbankdevelopers.cl/slack_community" target="_blank" rel="noopener"
            class="tbk-button secondary"><span class="underline text-tbk-red">Comunidad Slack</span></a>

        <button id="dark-mode" class="dark-mode-btn" data-action="menu#toggleTheme">
            <%= image_tag "sun.svg", alt: "sun", class: "sun-img" %>
            <%= image_tag "moon.svg", alt: "moon", class: "moon-img" %>
        </button>
    </div>

</div>

app/views/partials/_navigation.html.erb
<% if defined?(navigation) && navigation && !navigation.empty? %>
  <div class="nav-container" data-controller="nav-highlighter">
    <span class="nav-title">Contenido en esta página</span>
    <ul class="nav-list">
      <% navigation.each do |section_id, title| %>
        <li>
          <a href="#<%= section_id %>" class="item" data-nav-highlighter-target="link">
            <%= title %>
          </a>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/partials/_sidebar.html.erb
<%# app/views/partials/_sidebar.html.erb (Versión con Stimulus) %>

<aside class="tbk-sidebar" id="sidebar-desk" data-controller="sidebar"
       data-sidebar-target="sidebar"> 
    <div class="toogle-btn-container">
        <button class="tbk-toggle-btn" id="toggle-sidebar-btn" data-action="sidebar#toggleSidebar"
                data-sidebar-target="toggleButton"> 
            &lt;
        </button>
    </div>

    <nav class="sidebar-content" id="sidebar-content" data-sidebar-target="sidebarContent">
        <div>
            <p class="tbk-sidebar-item-title">Webpay Plus</p>
            <ul>
                <li style="margin-bottom:20px;">
                    <button class="sidebar-collapsible-title" data-collapsible="webpay-plus"
                            data-action="sidebar#toggleCollapsible" data-sidebar-target="collapsibleTitle">
                        <span class="general-text">Webpay Plus</span>
                        <%= image_tag 't-arrow.svg', class: 'arrow', alt: 't-arrow', width: 24, height: 24, data: { sidebar_target: "arrow" } %>
                    </button>
                    <ul class="collapsible-content" id="collapse-webpay-plus" data-sidebar-target="collapsibleContent">
                        <li class="collapsible-items">
                            <a href="<%= webpay_plus_create_path %>" class="tbk-sidebar-item" data-sidebar-target="sidebarItem">
                                Flujo Completo
                            </a>
                        </li>
                    </ul>
                </li>
              
                <li style="margin-bottom:20px;">
                    <button class="sidebar-collapsible-title" data-collapsible="webpay-plus-mall"
                            data-action="sidebar#toggleCollapsible" data-sidebar-target="collapsibleTitle">
                        <span class="general-text">Webpay Plus Mall</span>
                        <%= image_tag 't-arrow.svg', class: 'arrow', alt: 't-arrow', width: 24, height: 24, data: { sidebar_target: "arrow" } %>
                    </button>
                    <ul class="collapsible-content" id="collapse-webpay-plus-mall" data-sidebar-target="collapsibleContent">
                        <li class="collapsible-items">
                            <a href="<%= webpay_mall_create_path %>" class="tbk-sidebar-item" data-sidebar-target="sidebarItem">
                                Flujo Completo
                            </a>
                        </li>
                    </ul>
                </li>

                <li style="margin-bottom:20px;">
                    <button class="sidebar-collapsible-title" data-collapsible="webpay-plus-deferred"
                            data-action="sidebar#toggleCollapsible" data-sidebar-target="collapsibleTitle">
                        <span class="general-text">Webpay Plus Diferido</span>
                        <%= image_tag 't-arrow.svg', class: 'arrow', alt: 't-arrow', width: 24, height: 24, data: { sidebar_target: "arrow" } %>
                    </button>
                    <ul class="collapsible-content" id="collapse-webpay-plus-deferred" data-sidebar-target="collapsibleContent">
                        <li class="collapsible-items">
                            <a href="<%= webpay_deferred_create_path %>" class="tbk-sidebar-item" data-sidebar-target="sidebarItem">
                                Flujo Completo
                            </a>
                        </li>
                    </ul>
                </li>

                <li style="margin-bottom:20px;">
                    <button class="sidebar-collapsible-title" data-collapsible="webpay-mall-diferido"
                            data-action="sidebar#toggleCollapsible" data-sidebar-target="collapsibleTitle">
                        <span class="general-text">Webpay Plus Mall Diferido</span>
                        <%= image_tag 't-arrow.svg', class: 'arrow', alt: 't-arrow', width: 24, height: 24, data: { sidebar_target: "arrow" } %>
                    </button>
                    <ul class="collapsible-content" id="collapse-webpay-mall-diferido" data-sidebar-target="collapsibleContent">
                        <li class="collapsible-items">
                            <a href="<%= webpay_mall_deferred_create_path %>" class="tbk-sidebar-item" data-sidebar-target="sidebarItem">
                                Flujo Completo
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
            <hr class="sidebar-divider" />
        </div>

        <div>
            <p class="tbk-sidebar-item-title">Webpay Oneclick</p>
            <ul>

                <li style="margin-bottom:20px;">
                    <button class="sidebar-collapsible-title" data-collapsible="oneclick-mall"
                            data-action="sidebar#toggleCollapsible" data-sidebar-target="collapsibleTitle">
                        <span class="general-text">Oneclick Mall</span>
                        <%= image_tag 't-arrow.svg', class: 'arrow', alt: 't-arrow', width: 24, height: 24, data: { sidebar_target: "arrow" } %>
                    </button>
                    <ul class="collapsible-content" id="collapse-oneclick-mall" data-sidebar-target="collapsibleContent">
                        <li class="collapsible-items">
                            <a href="<%= oneclick_mall_start_path %>" class="tbk-sidebar-item" data-sidebar-target="sidebarItem">
                                Flujo Completo
                            </a>
                        </li>
                    </ul>
                </li>


                <li style="margin-bottom:20px;">
                    <button class="sidebar-collapsible-title" data-collapsible="oneclick-mall-deferred"
                            data-action="sidebar#toggleCollapsible" data-sidebar-target="collapsibleTitle">
                        <span class="general-text">Oneclick Mall Diferido</span>
                        <%= image_tag 't-arrow.svg', class: 'arrow', alt: 't-arrow', width: 24, height: 24, data: { sidebar_target: "arrow" } %>
                    </button>
                    <ul class="collapsible-content" id="collapse-oneclick-mall-deferred" data-sidebar-target="collapsibleContent">
                        <li class="collapsible-items">
                            <a href="<%= oneclick_mall_deferred_start_path %>" class="tbk-sidebar-item" data-sidebar-target="sidebarItem">
                                Flujo Completo
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
            <hr class="sidebar-divider" />
        </div>
    </nav>
</aside>


<div data-sidebar-target="bodyContainer" class="body-container-placeholder" style="display: none;"></div>