config/routes.rb
Rails.application.routes.draw do
  get "product_index/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get 'webpay-plus/refresh_respond_data_json', to: 'webpay_plus#refresh_respond_data_json', as: :refresh_webpay_plus_json
  get '"webpay-mall/refresh_respond_data_json', to: 'webpay_plus_mall#refresh_respond_data_json', as: :refresh_webpay_mall_json
  get 'webpay-plus-diferido/refresh_respond_data_json', to: 'webpay_plus_deferred#refresh_respond_data_json', as: :refresh_webpay_plus_deferred_json
  get 'webpay-mall-diferido/refresh_respond_data_json', to: 'webpay_plus_mall_deferred#refresh_respond_data_json', as: :refresh_webpay_mall_deferred_json
  root to: "product_index#index"

  get "/oneclick-mall", to: "home#oneclick_mall", as: :oneclick_mall
  get "/transaccion-completa", to: "home#transaccion_completa", as: :transaccion_completa
  get "/patpass-comercio", to: "home#patpass_comercio", as: :patpass_comercio

  # --- API Reference ---
  get "/api-reference/webpay-plus", to: "webpay_plus#show_operations", as: :webpay_plus_api_operations
  get "/api-reference/webpay-mall", to: "webpay_plus_mall#show_operations", as: :webpay_mall_api_operations
  get "/api-reference/webpay-plus-diferido", to: "webpay_plus_deferred#show_operations", as: :webpay_deferred_api_operations
  get "/api-reference/webpay-mall-diferido", to: "webpay_plus_mall_deferred#show_operations", as: :webpay_mall_deferred_api_operations

  # --- Webpay Plus ---
  # Controladores: WebpayPlusController
  get "webpay-plus/create", to: "webpay_plus#create", as: :webpay_plus_create
  match "webpay-plus/commit", to: "webpay_plus#commit", via: [ :get, :post ], as: :webpay_plus_commit
  get "webpay-plus/refund", to: "webpay_plus#refund", as: :webpay_plus_refund
  get "webpay-plus/status", to: "webpay_plus#status", as: :webpay_plus_status

  # --- Webpay Plus Mall ---
  # Controladores: WebpayPlusMallController
  get "webpay-mall/create", to: "webpay_plus_mall#create", as: :webpay_mall_create
  match "webpay-mall/commit", to: "webpay_plus_mall#commit", via: [ :get, :post ], as: :webpay_mall_commit
  get "webpay-mall/refund", to: "webpay_plus_mall#refund", as: :webpay_mall_refund
  get "webpay-mall/status", to: "webpay_plus_mall#status", as: :webpay_mall_status

  # --- Webpay Plus Diferido ---
  # Controladores: WebpayPlusDeferredController
  get "webpay-plus-diferido/create", to: "webpay_plus_deferred#create", as: :webpay_deferred_create
  match "webpay-plus-diferido/commit", to: "webpay_plus_deferred#commit", via: [ :get, :post ], as: :webpay_deferred_commit
  get "webpay-plus-diferido/capture", to: "webpay_plus_deferred#capture", as: :webpay_deferred_capture
  get "webpay-plus-diferido/refund", to: "webpay_plus_deferred#refund", as: :webpay_deferred_refund
  get "webpay-plus-diferido/status", to: "webpay_plus_deferred#status", as: :webpay_deferred_status

  # --- Webpay Plus Mall Diferido ---
  # Controladores: WebpayPlusMallDeferredController
  get "webpay-mall-diferido/create", to: "webpay_plus_mall_deferred#create", as: :webpay_mall_deferred_create
  match "webpay-mall-diferido/commit", to: "webpay_plus_mall_deferred#commit", via: [ :get, :post ], as: :webpay_mall_deferred_commit
  get "webpay-mall-diferido/capture", to: "webpay_plus_mall_deferred#capture", as: :webpay_mall_deferred_capture
  get "webpay-mall-diferido/refund", to: "webpay_plus_mall_deferred#refund", as: :webpay_mall_deferred_refund
  get "webpay-mall-diferido/status", to: "webpay_plus_mall_deferred#status", as: :webpay_mall_deferred_status

  # --- Oneclick Mall ---
  # Controladores: OneclickMallController
  get "oneclick-mall/start", to: "oneclick_mall#start", as: :oneclick_mall_start 
  get "oneclick-mall/finish", to: "oneclick_mall#finish", as: :oneclick_mall_finish
  get "oneclick-mall/authorize", to: "oneclick_mall#authorize", as: :oneclick_mall_authorize
  get "oneclick-mall/delete", to: "oneclick_mall#delete", as: :oneclick_mall_delete
  get "oneclick-mall/refund", to: "oneclick_mall#refund", as: :oneclick_mall_refund
  get "oneclick-mall/status", to: "oneclick_mall#status", as: :oneclick_mall_status

  # --- Oneclick Mall Diferido ---
  # Controladores: OneclickMallDeferredController
  get "oneclick-mall-diferido/start", to: "oneclick_mall_deferred#start", as: :oneclick_mall_deferred_start
  get "oneclick-mall-diferido/finish", to: "oneclick_mall_deferred#finish", as: :oneclick_mall_deferred_finish
  get "oneclick-mall-diferido/authorize", to: "oneclick_mall_deferred#authorize", as: :oneclick_mall_deferred_authorize
  get "oneclick-mall-diferido/delete", to: "oneclick_mall_deferred#delete", as: :oneclick_mall_deferred_delete
  get "oneclick-mall-diferido/status", to: "oneclick_mall_deferred#status", as: :oneclick_mall_deferred_status
  get "oneclick-mall-diferido/refund", to: "oneclick_mall_deferred#refund", as: :oneclick_mall_deferred_refund
  get "oneclick-mall-diferido/capture", to: "oneclick_mall_deferred#capture", as: :oneclick_mall_deferred_capture
end

app/controllers/oneclick_mall_deferred_controller.rb
class OneclickMallDeferredController < ApplicationController
  skip_before_action :verify_authenticity_token

  logger = Logger.new(STDOUT)
  ERROR_PAGE = "shared/error_page".freeze
  before_action :set_transbank_transaction

  def start
    begin
      @username = "User-#{rand(1000)}"
      @email = "user.#{rand(1000)}@example.com"
      @response_url = oneclick_mall_deferred_finish_url
      create_ins = {
        username: @username,
        email: @email,
        response_url: @response_url
      }
      session[:username] = @username
      session[:email] = @email
      @resp = @inscription.start(@username, @email, @response_url)  
      @request_data = create_ins
      @respond_data = @resp.with_indifferent_access
    rescue StandardError => e
      logger.error(e)
      flash[:alert] = "Ocurrió un error inesperado: #{e.message}"
      render ERROR_PAGE, locals: { error: e.message }
    end
  end

  def finish
    begin
      @req = params.as_json
      @token = @req["TBK_TOKEN"]
      @resp = @inscription.finish(@token)  
      @response_url = oneclick_mall_deferred_finish_url
      @respond_data = @resp.with_indifferent_access
      session[:tbk_user] = @respond_data[:tbk_user]
      @username = session[:username]
      @tbk_user = @respond_data[:tbk_user]
      @child_commerce_code1 = ::Transbank::Common::IntegrationCommerceCodes::ONECLICK_MALL_DEFERRED_CHILD1
      @child_commerce_code2 = ::Transbank::Common::IntegrationCommerceCodes::ONECLICK_MALL_DEFERRED_CHILD2
      @request_data  = {
        username: @username,
        tbk_user: @tbk_user
      }
    rescue StandardError => e
      logger.error(e)
      flash[:alert] = "Ocurrió un error inesperado: #{e.message}"
      render ERROR_PAGE, locals: { error: e.message }
    end
  end

  def delete
    begin
      @req = params.as_json
      @username = @req['username']
      @tbk_user = @req['tbk_user']
      @resp = @inscription.delete(@tbk_user, @username)
      @respond_data = {}
    rescue StandardError => e
      logger.error(e)
      flash[:alert] = "Ocurrió un error inesperado: #{e.message}"
      render ERROR_PAGE, locals: { error: e.message }
    end
  end

  def authorize
    begin
      @req = params.as_json
      @username = @req['username']
      @tbk_user = @req['tbk_user']
      @buy_order = "buyOrder_#{rand(1000)}"
      @child_commerce_code1 = @req['child_commerce_code1']
      @child_commerce_code2 = @req['child_commerce_code2']
      @child_commerce_amount1 = @req['child_commerce_amount1']
      @child_commerce_amount2 = @req['child_commerce_amount2']
      @child_commerce_installments1 = @req['child_commerce_installments1']
      @child_commerce_installments2 = @req['child_commerce_installments2']
      @details =[
        {
          commerce_code: @child_commerce_code1,
          buy_order: "childBuyOrder1_#{rand(1000)}",
          amount: @child_commerce_amount1,
          installments_number: @child_commerce_installments1
        },
        {
          commerce_code: @child_commerce_code2,
          buy_order: "childBuyOrder2_#{rand(1000)}",
          amount: @child_commerce_amount2,
          installments_number: @child_commerce_installments2
        }
      ]
      @resp = @tx.authorize(@username, @tbk_user, @buy_order, @details)
      @respond_data = @resp.with_indifferent_access
    rescue StandardError => e
      logger.error(e)
      flash[:alert] = "Ocurrió un error inesperado: #{e.message}"
      render ERROR_PAGE, locals: { error: e.message }
    end
  end

  def status
    begin
      @req = params.as_json
      @buy_order = params[:buy_order]
      @resp = @tx.status(@buy_order)
      @respond_data = @resp.with_indifferent_access
    rescue StandardError => e
      logger.error(e)
      flash[:alert] = "Ocurrió un error inesperado: #{e.message}"
      render ERROR_PAGE, locals: { error: e.message }
    end
  end

  def refund
    begin
      @req = params.as_json
      @buy_order = params[:buy_order] 
      @child_commerce_code = params[:child_commerce_code] 
      @child_buy_order = params[:child_buy_order] 
      @amount = params[:amount] 
      @resp = @tx.refund(@buy_order, @child_commerce_code, @child_buy_order, @amount)
      @respond_data = @resp.with_indifferent_access
    rescue StandardError => e
      logger.error(e)
      flash[:alert] = "Ocurrió un error inesperado: #{e.message}"
      render ERROR_PAGE, locals: { error: e.message }
    end
  end


  def capture
    begin
      @req = params.as_json
      @buy_order = params[:buy_order]
      @child_buy_order = params[:child_buy_order]
      @authorization_code = params[:authorization_code]
      @amount = params[:amount]
      @child_commerce_code = params[:child_commerce_code]

      @resp = @tx.capture(@child_commerce_code, @child_buy_order, @authorization_code, @amount)  
      @respond_data = @resp.with_indifferent_access
    rescue StandardError => e
      logger.error(e)
      flash[:alert] = "Ocurrió un error inesperado: #{e.message}"
      render ERROR_PAGE, locals: { error: e.message }
    end
  end

  def set_transbank_transaction
    environment = :integration
    commerce_code = ::Transbank::Common::IntegrationCommerceCodes::ONECLICK_MALL_DEFERRED
    api_key =  ::Transbank::Common::IntegrationApiKeys::WEBPAY

    options = Transbank::Webpay::Options.new(commerce_code, api_key, environment)
    @tx = Transbank::Webpay::Oneclick::MallTransaction.new(options)
    @inscription = Transbank::Webpay::Oneclick::MallInscription.new(options)
  end

end

app/views/oneclick_mall_deferred/authorize.html.erb
<%= render 'shared/breadcrumbs', breadcrumbs: [
  { label: 'Inicio', path: root_path },
  { label: 'Webpay Oneclick Mall Diferido', path: '/oneclick-mall-diferido/start' },
  { label: 'Autorizar pago', path: '/oneclick-mall-diferido/authorize' }
] %>

<h1>Webpay Oneclick Mall Diferido - Autorizar pago</h1>
<p class="mb-32">
  En este primer paso, procederemos a autorizar una transacción en la tarjeta que ha sido previamente inscrita.
</p>

<h2 id="request">Paso 1: Petición</h2>
<p class="mb-32">
  Ahora que contamos con el "username" y el "tbk_user" obtenidos durante la inscripción, estamos listos para
  autorizar transacciones en la tarjeta inscrita.
</p>

<pre>
  <code class="language-ruby">
    @details =[
        {
          commerce_code: "child_commerce_code",
          buy_order: "child_buy_order",
          amount: 1000,
          installments_number: 0
        },
        {
          commerce_code: "child_commerce_code2",
          buy_order: "child_buy_order2",
          amount: 5000,
          installments_number: 0
        }
      ]
    @resp = @tx.authorize(@username, @tbk_user, @buy_order, @details)
  </code>
</pre>

<h2 id="response">Paso 2: Respuesta</h2>
<p class="mb-32">
  Una vez que la transacción ha sido autorizada Transbank proporcionará la siguiente información. 
  Es fundamental conservar esta respuesta y verificar que el campo "response_code" 
  tenga un valor de cero y que el campo "status" sea "AUTHORIZED".
</p>

<pre>
  <code class="language-json"><%= JSON.pretty_generate(@respond_data) %></code>
</pre>

<h2>¡Casi listo!</h2>
<p class="mb-32">
  Ya puedes mostrar al usuario una página de éxito de la transacción. Debes tener en cuenta que la transacción 
  aun no ha sido capturada solo ha sido retenido el saldo en la tarjeta del Tarjetahabiente
</p>

<% @respond_data[:details].each do |detail| %>
  <%= form_with url: oneclick_mall_deferred_capture_path, method: :get do %>
    <%= hidden_field_tag :buy_order, @buy_order %>
    <div class="tbk-card">
      <div class="card-multi-field">
        <div class="input-container">
          <%= label_tag :child_commerce_code, "Código de comercio (tienda hija):", class: "tbk-label" %>
          <%= text_field_tag :child_commerce_code, detail[:commerce_code], class: "tbk-input-text" %>
        </div>
        <div class="input-container">
          <%= label_tag :child_buy_order, "Orden de compra (tienda hija):", class: "tbk-label" %>
          <%= text_field_tag :child_buy_order, detail[:buy_order], class: "tbk-input-text" %>
        </div>
        <div class="input-container">
          <%= label_tag :authorization_code, "Código de autorización (tienda hija):", class: "tbk-label" %>
          <%= text_field_tag :authorization_code, detail[:authorization_code], class: "tbk-input-text" %>
        </div>
        <div class="input-container">
          <%= label_tag :amount, "Monto a capturar (tienda hija):", class: "tbk-label" %>
          <%= text_field_tag :amount, detail[:amount], class: "tbk-input-text" %>
        </div>
      </div>
      <div class="tbk-card-footer">
        <%= submit_tag "CAPTURAR", class: "tbk-button primary" %>
      </div>
    </div>
  <% end %>
<% end %>

<%= link_to "CONSULTAR ESTADO",
            oneclick_mall_deferred_status_url(buy_order: @respond_data[:buy_order]),
            class: "tbk-button primary mb-32" %>

app/views/oneclick_mall_deferred/capture.html.erb
<%= render 'shared/breadcrumbs', breadcrumbs: [
  { label: 'Inicio', path: root_path },
  { label: 'Webpay Oneclick Mall Diferido', path: '/oneclick-mall-diferido/start' },
  { label: 'Capturar pago', path: '/oneclick-mall-diferido/capture' }
] %>

<h1>Webpay Oneclick Mall Diferido - Capturar transacción diferida</h1>
<p class="mb-32">
  En este paso debemos capturar la transacción para realmente capturar el dinero que había sido previamente
  reservado al hacer la transacción.
</p>

<h2 id="request">Paso 1: Petición</h2>
<p class="mb-32">
  Para capturar una transacción necesitaremos el código de comercio de la tienda hija y Orden de compra de la tienda hija, 
  Código de autorización y monto a capturar. Se hace de la siguiente manera.
</p>

<pre>
  <code class="language-ruby">
  @resp = @tx.capture(@child_commerce_code, @child_buy_order, @authorization_code, @amount)    
  </code>
</pre>

<h2 id="response">Paso 2: Respuesta</h2>
<p class="mb-32">
  Una vez creada la transacción, recibirás los siguientes datos de respuesta:
</p>

<pre>
  <code class="language-json"><%= JSON.pretty_generate(@respond_data) %></code>
</pre>

<h2 id="operations">Otras utilidades</h2>
<p class="mb-32">
  Luego de capturada la transacción puedes Reembolsar (reversar o anular) el pago dependiendo 
  de ciertas condiciones comerciales (Reversa en las primeras 3 horas de la captura, anulación posterior a eso). 
  También puedes consultar el estado de la transacción hasta 7 días después de realizada.
</p>

<form action="<%=oneclick_mall_deferred_refund_url %>" method="GET">
  <%= hidden_field_tag :buy_order, @buy_order %> 
  <%= hidden_field_tag :child_buy_order, @child_buy_order %> 
  <%= hidden_field_tag :authorization_code, @authorization_code %> 
  <%= hidden_field_tag :child_commerce_code, @child_commerce_code %> 
  <div class="tbk-refund-card mb-32">
    <div class="input-container">
      <label class="tbk-label" for="amount" >Monto a reembolsar:</label>
      <input type="text" id="amount" name="amount" class="tbk-input-text" value="<%= @respond_data[:captured_amount] %>" />
    </div>
    <div class="tbk-refund-button-container">
    </div>
    
    <div class="tbk-refund-button-container">
      <button class="tbk-button primary">REEMBOLSAR</button>
      <%= link_to "CONSULTAR ESTADO", oneclick_mall_deferred_status_url(buy_order: @buy_order), class: "tbk-button primary" %>
    </div>
  </div>
</form>  

app/views/oneclick_mall_deferred/delete.html.erb
<%= render 'shared/breadcrumbs', breadcrumbs: [
  { label: 'Inicio', path: root_path },
  { label: 'Webpay Oneclick Mall Diferido', path: '/oneclick-mall-diferido/start' },
  { label: 'Borrar usuario', path: '/oneclick-mall-diferido/delete' }
] %>

<h1>Webpay Oneclick Mall Diferido - Borrar usuario</h1>
<p class="mb-32">
    En este paso fundamental, procederemos a eliminar la inscripción del usuario y su medio de pago.
</p>

<h2 id="request">Paso 1: Petición</h2>
<p class="mb-32">
    Para llevar a cabo la eliminación, necesitas el "username" (Nombre de Usuario) y el "tbk_user". Realiza la
    llamada a MallInscription utilizando el siguiente código:
</p>

<pre>
  <code class="language-ruby">
  @resp = @inscription.delete(@tbk_user, @username)
  </code>
</pre>

<h2 id="response">Paso 2: Respuesta</h2>
<p class="mb-32">
    En caso de éxito, Transbank responderá con un status code 204 (No Content), y el SDK no retornará ningún valor. 
    La eliminación de la inscripción se ha realizado de manera exitosa.
</p>

<p class="mb-32">
    En el caso de que no se encuentre el "username" o el "tbk_user", Transbank responderá con un status code 404 (Not
    Found), y el SDK lanzará una excepción del tipo TransbankError.
</p>

<p class="mb-32">
    Este proceso garantiza una eliminación segura y eficiente de la inscripción del usuario y su medio de pago
    asociado. ¡Gracias por confiar en Transbank para tus operaciones seguras! Si tienes alguna pregunta, estamos
    aquí para ayudarte
</p>

app/views/oneclick_mall_deferred/finish.html.erb
<%= render 'shared/breadcrumbs', breadcrumbs: [
  { label: 'Inicio', path: root_path },
  { label: 'Webpay Oneclick Mall Diferido', path: '/oneclick-mall-diferido/start' },
  { label: 'Finalizar inscripción', path: '/oneclick-mall-diferido/finish' }
] %>

<h1>Webpay Oneclick Mall Diferido - Finalizar inscripción</h1>
<p class="mb-32">
  En esta fase, completaremos el proceso de inscripción, permitiéndonos posteriormente realizar cargos a la
  tarjeta que el tarjetahabiente haya inscrito.
</p>

<h2 id="data">Paso 1: Datos recibidos</h2>
<p class="mb-32">
  Después de finalizar el flujo en el formulario de inscripción, recibirás un GET con la siguiente información:
</p>

<pre>
  <code class="language-ruby">
  <%=@response_url%>?TBK_TOKEN=<%=@token%>
  </code>
</pre>

<h2 id="request">Paso 2: Petición de autorización</h2>
<p class="mb-32">
  Utiliza el token recibido para finalizar la Inscripción mediante una nueva llamada a Oneclick.
</p>

<pre>
  <code class="language-ruby">
  @resp = @inscription.finish(@token) 
  </code>
</pre>

<h2 id="response">Paso 3: Respuesta</h2>
<p class="mb-32">
  Transbank responderá con información crucial. Guarda estos detalles, ya que serán necesarios para autorizar
  transacciones futuras.
</p>

<pre>
  <code class="language-json"><%= JSON.pretty_generate(@respond_data) %></code>
</pre>

<h2 id="authorize">¡La tarjeta ya está inscrita!</h2>
<p class="mb-32">Con la inscripción exitosa se pueden autorizar transacciones.</p>

<h2>Autorizar una transacción</h2>
<p class="mb-32">
  Asegúrate de guardar los datos de la respuesta obtenidos durante la inscripción. Estos serán esenciales para
  llevar a cabo transacciones de manera efectiva.
</p>

<div class="mb-32">
  <%= render partial: 'shared/request_table', locals: { data: @request_data } %>
</div>

<p class="mt-32">
  Después de una inscripción exitosa, tienen dos opciones: autorizar un pago o borrar al usuario que se
  acaba de inscribir.
</p>

<%= form_with url: oneclick_mall_deferred_authorize_path, method: :get do %>
  <%= hidden_field_tag :username, @username %>
  <%= hidden_field_tag :tbk_user, @tbk_user %>
  <%= hidden_field_tag :child_commerce_code1, @child_commerce_code1 %>
  <%= hidden_field_tag :child_commerce_code2, @child_commerce_code2 %>
  <div class="tbk-card">
    <p class="mb-16">Tienda 1</p>
    <div class="card-multi-field">
      <div class="input-container">
        <%= label_tag :child_commerce_amount1, 'Monto:', class: 'tbk-label' %>
        <%= number_field_tag :child_commerce_amount1, 10000, class: 'tbk-input-text' %>
      </div>
      <div class="input-container">
        <%= label_tag :child_commerce_installments1, 'Cuotas:', class: 'tbk-label' %>
        <%= number_field_tag :child_commerce_installments1, 0, class: 'tbk-input-text' %>
      </div>
    </div>

    <p class="mb-16 mt-32">Tienda 2</p>
    <div class="card-multi-field">
      <div class="input-container">
        <%= label_tag :child_commerce_amount2, 'Monto:', class: 'tbk-label' %>
        <%= number_field_tag :child_commerce_amount2, 5000, class: 'tbk-input-text' %>
      </div>
      <div class="input-container">
        <%= label_tag :child_commerce_installments2, 'Cuotas:', class: 'tbk-label' %>
        <%= number_field_tag :child_commerce_installments2, 0, class: 'tbk-input-text' %>
      </div>
    </div>

    <div class="tbk-card-footer">
      <%= submit_tag 'AUTORIZAR', class: 'tbk-button primary' %>
    </div>
  </div>
<% end %>

<%= link_to "BORRAR USUARIO", oneclick_mall_deferred_delete_url(tbk_user: @tbk_user, username: @username), class: "tbk-button primary" %>

app/views/oneclick_mall_deferred/refund.html.erb
<%= render 'shared/breadcrumbs', breadcrumbs: [
  { label: 'Inicio', path: root_path },
  { label: 'Webpay Oneclick Mall Diferido', path: '/oneclick-mall-diferido/start' },
  { label: 'Reembolsar', path: '/oneclick-mall-diferido/refund' }
] %>

<h1>Webpay Oneclick Mall Diferido - Reembolsar</h1>
<p class="mb-32">
    En esta etapa, tienes la opción de solicitar el reembolso del monto al titular de la tarjeta.
    Dependiendo del monto y el tiempo transcurrido desde la transacción, este proceso podría resultar en una Reversa
    o Anulación, dependiendo de ciertas condiciones (Reversa en las primeras 3 horas de la autorización, anulación
    posterior a eso), o una Anulación parcial si el monto es menor al total.
    Las anulaciones parciales para tarjetas débito y prepago no están soportadas.
</p>

<h2 id="request">Paso 1 - Petición:</h2>
<p class="mb-16">
    Para realizar el reembolso, necesitarás la siguiente información:
</p>

<ul class="bullet-list mb-32">
    <li>Orden de compra de la transacción.</li>
    <li>Monto que deseas reversar.</li>
    <li>Código de comercio de la tienda hijo.</li>
    <li>Orden de compra del detalle de la transacción.</li>
</ul>

<p class="mb-32">
    Ten en cuenta que si anulas el monto total, puede ser una Reversa o Anulación, 
    dependiendo de ciertas condiciones (Reversa en las primeras 3 horas de la autorización, anulación posterior a eso), 
    o una Anulación parcial si el monto es menor al total. Las anulaciones parciales para tarjetas débito y prepago no están soportadas.
</p>

<p class="mb-32">
    En <a href="https://www.transbankdevelopers.cl/producto/webpay#anulaciones-y-reversas" class="tbk-link">este
        link
    </a> podrás ver mayor información sobre las condiciones y casos para anular o reversar transacciones.
</p>

<pre>
  <code class="language-ruby">
  @resp = @tx.refund(@buy_order, @child_commerce_code, @child_buy_order, @amount)
  </code>
</pre>

<h2 id="response">Paso 2 - Respuesta:</h2>
<p class="mb-32">
    Transbank responderá con el resultado de la reversa o anulación. Analiza esta respuesta para confirmar que el
    reembolso se ha procesado correctamente.
</p>

<pre>
  <code class="language-json"><%= JSON.pretty_generate(@respond_data) %></code>
</pre>

<%= link_to "CONSULTAR ESTADO",
              oneclick_mall_deferred_status_url(buy_order: @buy_order),
              class: "tbk-button primary mb-32" %>

app/views/oneclick_mall_deferred/status.html.erb
<%= render 'shared/breadcrumbs', breadcrumbs: [
  { label: 'Inicio', path: root_path },
  { label: 'Webpay Oneclick Mall Diferido', path: '/oneclick-mall-diferido/start' },
  { label: 'Consultar estado de transacción', path: '/oneclick-mall-diferido/status' }
] %>

<h1>Webpay Oneclick Mall Diferido - Consultar estado de transacción</h1>
    <p class="mb-32">Puedes solicitar el estado de una transacción hasta 7 días después de su realización. No hay
        límite
        de solicitudes de este tipo durante ese período. Sin embargo, una vez pasados los 7 días, ya no podrás revisar
        su estado.
    </p>

    <h2 id="request">Paso 1 - Petición:</h2>
    <p class="mb-32">
        Para realizar la consulta, necesitarás el "buy_order" de la transacción de interés. Utiliza este identificador
        para efectuar una llamada a MallTransaction.
    </p>

<pre>
  <code class="language-ruby">
  @resp = @tx.status(@buy_order)
  </code>
</pre>

    <h2 id="response">Paso 2: Respuesta</h2>
    <p class="mb-32">
        Transbank responderá con la siguiente información. Asegúrate de guardar esta respuesta, y la única validación
        necesaria es que el campo "response_code" sea igual a cero.
    </p>

<pre>
  <code class="language-json"><%= JSON.pretty_generate(@respond_data) %></code>
</pre>