config/routes.rb
Rails.application.routes.draw do
  get "product_index/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get 'webpay-plus/refresh_respond_data_json', to: 'webpay_plus#refresh_respond_data_json', as: :refresh_webpay_plus_json
  get '"webpay-mall/refresh_respond_data_json', to: 'webpay_plus_mall#refresh_respond_data_json', as: :refresh_webpay_mall_json
  get 'webpay-plus-diferido/refresh_respond_data_json', to: 'webpay_plus_deferred#refresh_respond_data_json', as: :refresh_webpay_plus_deferred_json
  get 'webpay-mall-diferido/refresh_respond_data_json', to: 'webpay_plus_mall_deferred#refresh_respond_data_json', as: :refresh_webpay_mall_deferred_json
  root to: "product_index#index"

  get "/oneclick-mall", to: "home#oneclick_mall", as: :oneclick_mall
  get "/transaccion-completa", to: "home#transaccion_completa", as: :transaccion_completa
  get "/patpass-comercio", to: "home#patpass_comercio", as: :patpass_comercio

  # --- API Reference ---
  get "/api-reference/webpay-plus", to: "webpay_plus#show_operations", as: :webpay_plus_api_operations
  get "/api-reference/webpay-mall", to: "webpay_plus_mall#show_operations", as: :webpay_mall_api_operations
  get "/api-reference/webpay-plus-diferido", to: "webpay_plus_deferred#show_operations", as: :webpay_deferred_api_operations
  get "/api-reference/webpay-mall-diferido", to: "webpay_plus_mall_deferred#show_operations", as: :webpay_mall_deferred_api_operations

  # --- Webpay Plus ---
  # Controladores: WebpayPlusController
  get "webpay-plus/create", to: "webpay_plus#create", as: :webpay_plus_create
  match "webpay-plus/commit", to: "webpay_plus#commit", via: [ :get, :post ], as: :webpay_plus_commit
  get "webpay-plus/refund", to: "webpay_plus#refund", as: :webpay_plus_refund
  get "webpay-plus/status", to: "webpay_plus#status", as: :webpay_plus_status

  # --- Webpay Plus Mall ---
  # Controladores: WebpayPlusMallController
  get "webpay-mall/create", to: "webpay_plus_mall#create", as: :webpay_mall_create
  match "webpay-mall/commit", to: "webpay_plus_mall#commit", via: [ :get, :post ], as: :webpay_mall_commit
  get "webpay-mall/refund", to: "webpay_plus_mall#refund", as: :webpay_mall_refund
  get "webpay-mall/status", to: "webpay_plus_mall#status", as: :webpay_mall_status

  # --- Webpay Plus Diferido ---
  # Controladores: WebpayPlusDeferredController
  get "webpay-plus-diferido/create", to: "webpay_plus_deferred#create", as: :webpay_deferred_create
  match "webpay-plus-diferido/commit", to: "webpay_plus_deferred#commit", via: [ :get, :post ], as: :webpay_deferred_commit
  get "webpay-plus-diferido/capture", to: "webpay_plus_deferred#capture", as: :webpay_deferred_capture
  get "webpay-plus-diferido/refund", to: "webpay_plus_deferred#refund", as: :webpay_deferred_refund
  get "webpay-plus-diferido/status", to: "webpay_plus_deferred#status", as: :webpay_deferred_status

  # --- Webpay Plus Mall Diferido ---
  # Controladores: WebpayPlusMallDeferredController
  get "webpay-mall-diferido/create", to: "webpay_plus_mall_deferred#create", as: :webpay_mall_deferred_create
  match "webpay-mall-diferido/commit", to: "webpay_plus_mall_deferred#commit", via: [ :get, :post ], as: :webpay_mall_deferred_commit
  get "webpay-mall-diferido/capture", to: "webpay_plus_mall_deferred#capture", as: :webpay_mall_deferred_capture
  get "webpay-mall-diferido/refund", to: "webpay_plus_mall_deferred#refund", as: :webpay_mall_deferred_refund
  get "webpay-mall-diferido/status", to: "webpay_plus_mall_deferred#status", as: :webpay_mall_deferred_status

  # --- Oneclick Mall ---
  # Controladores: OneclickMallController
  get "oneclick-mall/start", to: "oneclick_mall#start", as: :oneclick_mall_start 
  get "oneclick-mall/finish", to: "oneclick_mall#finish", as: :oneclick_mall_finish
  get "oneclick-mall/authorize", to: "oneclick_mall#authorize", as: :oneclick_mall_authorize
  get "oneclick-mall/delete", to: "oneclick_mall#delete", as: :oneclick_mall_delete
  get "oneclick-mall/refund", to: "oneclick_mall#refund", as: :oneclick_mall_refund
  get "oneclick-mall/status", to: "oneclick_mall#status", as: :oneclick_mall_status

  # --- Oneclick Mall Diferido ---
  # Controladores: OneclickMallDeferredController
  get "oneclick-mall-diferido/start", to: "oneclick_mall_deferred#start", as: :oneclick_mall_deferred_start
  get "oneclick-mall-diferido/finish", to: "oneclick_mall_deferred#finish", as: :oneclick_mall_deferred_finish
  get "oneclick-mall-diferido/authorize", to: "oneclick_mall_deferred#authorize", as: :oneclick_mall_deferred_authorize
  get "oneclick-mall-diferido/delete", to: "oneclick_mall_deferred#delete", as: :oneclick_mall_deferred_delete
  get "oneclick-mall-diferido/status", to: "oneclick_mall_deferred#status", as: :oneclick_mall_deferred_status
  get "oneclick-mall-diferido/refund", to: "oneclick_mall_deferred#refund", as: :oneclick_mall_deferred_refund
  get "oneclick-mall-diferido/capture", to: "oneclick_mall_deferred#capture", as: :oneclick_mall_deferred_capture
end

app/controllers/webpay_plus_deferred_controller.rb
require 'logger'

class WebpayPlusDeferredController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [ :commit, :refund ]

  PRODUCT = "Webpay Plus Diferido".freeze
  logger = Logger.new(STDOUT)

  before_action :set_transbank_transaction

  def create
    begin
      create_tx = {
        buy_order: "O-#{SecureRandom.random_number(1..10000)}",
        session_id: "S-#{SecureRandom.random_number(1..10000)}",
        return_url: webpay_deferred_commit_url,
        amount: SecureRandom.random_number(1000..2000)
      }
      @resp = @tx.create(create_tx[:buy_order], create_tx[:session_id], create_tx[:amount], create_tx[:return_url])
      @request_data = create_tx
      @respond_data = @resp.with_indifferent_access
    rescue StandardError => e
      logger.error(e)
      flash[:alert] = "Ocurrió un error inesperado: #{e.message}"
      render "shared/error_page", locals: { error: e.message }
    end
  end

  def commit
    begin
      @request_data = params.except(:controller, :action)
      @product_name = PRODUCT
      @create_url = webpay_deferred_create_url
      if params.key?("TBK_TOKEN") && params.key?("token_ws")
        @view_template = "error/webpay/form_error"
      elsif params.key?("TBK_TOKEN")
        # Pago abortado
        @view_template = "error/webpay/aborted"
        @resp = @tx.status(params["TBK_TOKEN"])
        @respond_data = @resp.with_indifferent_access
      elsif params.key?("token_ws")
        # Flujo normal: 'webpay.commit'
        @resp = @tx.commit(params["token_ws"])
        @view_template = "webpay_plus_deferred/commit"
        @token = params["token_ws"]
        @returnUrl = webpay_deferred_commit_url
        @respond_data = @resp.with_indifferent_access
      else
        # Timeout o un caso no manejado
        @view_template = "error/webpay/timeout"
      end

      render @view_template

    rescue StandardError => e
      logger.error(e)
      flash[:alert] = "Ocurrió un error inesperado en commit: #{e.message}"
      render "shared/error_page", locals: { error: e.message }
    end
  end

  def refund
    begin
      req_params = params.except(:_token)

      token_to_refund = req_params[:token]
      amount_to_refund = req_params[:amount].to_i

      @resp = @tx.refund(token_to_refund, amount_to_refund)
      @token = token_to_refund
      @respond_data = @resp.with_indifferent_access
    rescue StandardError => e
      logger.error(e)
      flash[:alert] = "Ocurrió un error inesperado en refund: #{e.message}"
      render "shared/error_page", locals: { error: e.message }
    end
  end

  def status
    begin
      token = params[:token]
      @resp = @tx.status(token)
      @request_data = params
      @respond_data = @resp.with_indifferent_access
    rescue StandardError => e
      logger.error(e)
      flash[:alert] = "Ocurrió un error inesperado en status: #{e.message}"
      @resp = nil
      render "shared/error_page", locals: { error: e.message }
    end
  end

  def capture
    begin
      @req = params.as_json
      @token = params[:token]
      @buy_order = params[:buy_order]
      @authorization_code = params[:authorization_code]
      @amount = params[:amount]
      @resp = @tx.capture(@token, @buy_order, @authorization_code, @amount)  
      @respond_data = @resp.with_indifferent_access
    rescue StandardError => e
      logger.error(e)
      flash[:alert] = "Ocurrió un error inesperado en capture: #{e.message}"
      @resp = nil
      render "shared/error_page", locals: { error: e.message }
    end
  end

  def refresh_respond_data_json
    @respond_data = create_transaction.with_indifferent_access
    render json: @respond_data
  end
  
  private

  def create_transaction
   create_tx = {
      buy_order: "O-#{SecureRandom.random_number(1..10000)}",
      session_id: "S-#{SecureRandom.random_number(1..10000)}",
      return_url: webpay_deferred_commit_url,
      amount: SecureRandom.random_number(1000..2000)
    }
    @resp = @tx.create(create_tx[:buy_order], create_tx[:session_id], create_tx[:amount], create_tx[:return_url])
  end

  def set_transbank_transaction
    environment = :integration
    commerce_code = ::Transbank::Common::IntegrationCommerceCodes::WEBPAY_PLUS_DEFERRED
    api_key =  ::Transbank::Common::IntegrationApiKeys::WEBPAY

    options = Transbank::Webpay::Options.new(commerce_code, api_key, environment)
    @tx = Transbank::Webpay::WebpayPlus::Transaction.new(options)
  end
end

app/views/webpay_plus_deferred/capture.html.erb
<%= render 'shared/breadcrumbs', breadcrumbs: [
  { label: 'Inicio', path: root_path },
  { label: 'Webpay Plus Diferido', path: '/webpay-plus-diferido/create' },
  { label: 'Capturar transacción diferida', path: '/webpay-plus-diferido/capture' }
] %>

<h1>Webpay Plus Diferido - Capturar transacción diferida</h1>
<p class="mb-32">
  En este paso debemos capturar la transacción para realmente capturar el dinero que había sido previamente
  reservado al hacer la transacción.
</p>

<h2 id="request">Paso 1: Petición</h2>
<p class="mb-32">
  Para capturar una transacción necesitaremos el Token, Orden de compra, Código de autorización y monto a
  capturar. Se hace de la siguiente manera.
</p>

<pre>
  <code class="language-ruby">
  @resp = @tx.capture(@token, @buy_order, @authorization_code, @amount)  
  </code>
</pre>

  <h2 id="response">Paso 2: Respuesta</h2>
  <p class="mb-32">
    Transbank contestará con lo siguiente. Debes guardar esta información, lo único que debes validar
    es que response_code sea igual a cero.
  </p>

<pre>
  <code class="language-json"><%= JSON.pretty_generate(@respond_data) %></code>
</pre>

<h2 id="operations">Otras utilidades</h2>
<p class="mb-32">
  Luego de capturada la transacción puedes Reembolsar (reversar o anular) el pago dependiendo 
  de ciertas condiciones comerciales (Reversa en las primeras 3 horas de la captura, anulación posterior a eso). 
  También puedes consultar el estado de la transacción hasta 7 días después de realizada.
</p>

<form action="<%=webpay_deferred_refund_url %>" method="GET">
  <%= hidden_field_tag :token, @token, class: "tbk-input-text" %> 
  <div class="tbk-refund-card mb-32">
    <div class="input-container">
      <label class="tbk-label" for="amount" >Monto a reembolsar:</label>
      <input type="text" name="amount" class="tbk-input-text" value="<%= @respond_data[:captured_amount] %>" />
    </div>
    <div class="tbk-refund-button-container">
    </div>
    
    <div class="tbk-refund-button-container">
      <button class="tbk-button primary">REEMBOLSAR</button>
      <%= link_to "CONSULTAR ESTADO", webpay_deferred_status_url(token: @token), class: "tbk-button primary" %>
    </div>
  </div>
</form>  

app/views/webpay_plus_deferred/commit.html.erb
<%= render 'shared/breadcrumbs', breadcrumbs: [
  { label: 'Inicio', path: root_path },
  { label: 'Webpay Plus Diferido', path: '/webpay-plus-diferido/create' },
  { label: 'Confirmar transacción', path: '/webpay-plus-diferido/commit' }
] %>

  <h1>Webpay Plus Diferido - Confirmar transacción</h1>

  <p class="mb-32">
    En este paso es importante confirmar la transacción para notificar a Transbank que hemos recibido exitosamente los detalles de la transacción.
    <b>Es importante destacar que si la confirmación no se realiza, la transacción será caducada.</b>
  </p>

  <h2 id="data">Paso 1 - Datos recibidos:</h2>
  <ul class="mb-32">
    <p class="m-32">
      Después de completar el flujo en el formulario de pago, recibirás un GET con la siguiente información:
    </p>
  </ul>

<pre>
  <code class="language-ruby">
  <%=@returnUrl%>?token_ws=<%=@token%>
  </code>
</pre>

  <h2 id="request">Paso 2 - Petición:</h2>
  <p class="mb-32">
    Utilizarás el token recibido para confirmar la transacción mediante el SDK.
  </p>

<pre>
  <code class="language-ruby">
  @resp = @transaction.commit(@token)
  </code>
</pre>

  <h2 id="response">Paso 3 - Respuesta:</h2>
  <p class="mb-32">
    Una vez que la transacción ha sido confirmada, Transbank proporcionará la siguiente información. 
    Es fundamental conservar esta respuesta y verificar que el campo "response_code" tenga un valor de cero y que el campo "status" sea "AUTHORIZED".
  </p>

<pre>
  <code class="language-json"><%= JSON.pretty_generate(@respond_data) %></code>
</pre>

<%= render "messages/commit_deferred_message"  %>

<form action="<%=webpay_deferred_capture_url %>" method="GET">
  <%= hidden_field_tag :token, @token, class: "tbk-input-text" %> 
  <%= hidden_field_tag :authorization_code, @respond_data[:authorization_code], class: "tbk-input-text" %> 
  <%= hidden_field_tag :buy_order, @respond_data[:buy_order], class: "tbk-input-text" %> 
  <div class="tbk-card mb-32">
    <div class="tbk-button-container">
       <p class="mb-32">Capturar la transacción para realmente capturar el dinero que habia sido previamente
                reservado.</p>
    </div>
    <div class="tbk-capture-section">
        <div class="input-container">
          <label class="tbk-label" for="amount" >Monto a capturar:</label>
          <input type="text" name="amount" class="tbk-input-text" value="<%= @respond_data[:amount] %>" />
        </div>
        <div class="tbk-button-container">
        </div>
        <div class="tbk-button-container">
          <button class="tbk-button primary">CAPTURAR</button>
          <%= link_to "CONSULTAR ESTADO", webpay_deferred_status_url(token: @token), class: "tbk-button primary" %>
        </div>
    </div>

  </div>
</form>

app/views/webpay_plus_deferred/create.html.erb
<%= render 'shared/breadcrumbs', breadcrumbs: [
  { label: 'Inicio', path: root_path },
  { label: 'Webpay Plus Diferido', path: '/webpay-plus-diferido/create' }
] %>

<h1>Webpay Plus Diferido - Creación de transacción</h1>
<p class="mb-32">
  En esta etapa, se procederá a la creación de una transacción con el fin de obtener un identificador único.
  Esto nos permitirá redirigir al Tarjetahabiente hacia el formulario de pago en el siguiente paso.
</p>

<p class="mb-32">
  Todas las transacciones en este proyecto de ejemplo son realizadas en
          ambiente de integración.
</p>

<h2 id="request">Paso 1: Petición</h2>
<ol class="bullet-list mb-32">
  <li>Comienza por importar la librería WebpayPlus en tu proyecto.</li>
  <li>Luego, crea una transacción utilizando las funciones proporcionadas mediante el SDK.</li>
</ol>

<pre>
  <code class="language-ruby">
  options = Transbank::Webpay::Options.new(commerce_code, api_key, environment)
  @tx = Transbank::Webpay::WebpayPlus::Transaction.new(options)
  @resp = @transaction.create(buy_order, session_id, amount, return_url)
  </code>
</pre>

<h2 id="response">Paso 2: Respuesta</h2>
<p class="mb-32">
  Una vez que hayas creado la transacción, aquí encontrarás los datos de respuesta generados por el proceso.
</p>

<pre>
  <code id="respond-data-json" class="language-json"><%= JSON.pretty_generate(@respond_data) %></code>
</pre>

<h2 id="form">Paso 3: Creación del formulario</h2>
<p class="mb-32">
  Utiliza estos datos de respuesta para redireccionar al usuario al formulario de pago al Tarjetahabiente.
  Este formulario será la interfaz a través de la cual el usuario realizará su transacción.
</p>

<pre>
  <code class="language-html">
<%= h(<<~HTML)
<form action="https://webpay3gint.transbank.cl/webpayserver/initTransaction" method="POST">
  <input type="hidden" name="token_ws" value="#{@respond_data["token"]}" />
  <input type="submit" value="Pagar" />
</form>
HTML
%>
  </code>
</pre>

<h2 id="example">Ejemplo</h2>
<p class="mb-32">
  Para llevar a cabo una transacción de compra en nuestro sistema, primero debemos crear la transacción. Utilizaremos
  los siguientes datos para configurar la transacción:
</p>

<div class="mb-32">
  <%= render partial: 'shared/request_table', locals: { data: @request_data } %>
</div>

<p class="mb-32">
  Por último, con la respuesta del servicio que confirma la creación de la transacción, procedemos a crear el
  formulario de pago. Para fines de este ejemplo, haremos visible el campo "token_ws", el cual es esencial para
  completar el proceso de pago de manera exitosa.
</p>

<span>
  Antes de continuar al formulario de Webpay, asegúrate de contar con los datos de las tarjetas de prueba que están en la
  <%= link_to 'documentación.', 'https://transbankdevelopers.cl/documentacion/como_empezar#tarjetas-de-prueba', class: 'tbk-link' %>
</span>

<form action="<%= @respond_data[:url] %>" method="POST">
  <div class="tbk-card">
    <span class="tbk-card-title">Formulario de redirección</span>
    <label class="tbk-label" for="token_ws">Token</label>
    <input id="token-input" type="text" name="token_ws" class="tbk-input-text" value="<%= @respond_data[:token] %>" />
    <div class="tbk-card-footer">
      <button class="tbk-button primary">PAGAR</button>
    </div>
  </div>
</form>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    function updateRespondData() {
      fetch("<%= refresh_webpay_plus_json_path %>")
        .then(response => response.json())
        .then(data => {
          document.getElementById("respond-data-json").textContent = JSON.stringify(data, null, 2);
          document.getElementById("token-input").value = data.token || "";
        })
        .catch(error => console.error("Error al actualizar los datos"));
    }
   
    setInterval(updateRespondData, 300000);
  });
</script>

app/views/webpay_plus_deferred/refund.html.erb
<%= render 'shared/breadcrumbs', breadcrumbs: [
  { label: 'Inicio', path: root_path },
  { label: 'Webpay Plus Diferido', path: '/webpay-plus-diferido/create' },
  { label: 'Reembolsar', path: '/webpay-plus-diferido/refund' }
] %>

<h1>Webpay Plus Diferido - Reembolsar</h1>
<p class="mb-32">
  En esta etapa, tienes la opción de solicitar el reembolso del monto al titular de la tarjeta.
  Dependiendo del monto y el tiempo transcurrido desde la transacción, este proceso podría resultar en una Reversa
  o Anulación, dependiendo de ciertas condiciones (Reversa en las primeras 3 horas de la autorización, anulación
  posterior a eso), o una Anulación parcial si el monto es menor al total.
  Las anulaciones parciales para tarjetas débito y prepago no están soportadas.
</p>

<h2 id="request">Paso 1 - Petición:</h2>
<p class="mb-32">
  Para llevar a cabo el reembolso, necesitas proporcionar el token de la transacción y el monto que
  deseas reversar.
</p>
<p class="mb-32">
  Las transacciones de Webpay se pueden anular o reversar dadas algunas condiciones. Para cualquiera
  de éstas operaciones se utiliza el mismo servicio web que discernirá si se realizará una reversa o una
  anulación.

  Para poder ejecutar una reversa ésta debe ser realizada antes de las 3 horas de efectuada la confirmación por el
  monto total y en compras con tarjeta de crédito, débito o prepago.

  Una vez pasadas las tres horas, siempre se ejecutará una anulación.
</p>
<ul class="bullet-list mb-32">
  <li>En transacciones con tarjeta de débito o prepago solo es posible anular por el monto total.</li>
  <li>En transacciones con tarjeta de crédito puedes anular por cualquier monto igual o menor al total de la compra.</li>
  <li>No se pueden hacer Anulaciones parciales de compras con cuotas.</li>
</ul>

<p class="mb-32">
  En
  <%= link_to 'este link', 'https://www.transbankdevelopers.cl/producto/webpay#anulaciones-y-reversas', class: 'tbk-link', target: '_blank' %>
  podrás ver mayor información sobre las condiciones y casos para anular o reversar transacciones.
</p>

<pre>
  <code class="language-ruby">
  @resp = @transaction.refund(@token, @amount)
  </code>
</pre>

<h2 id="response">Paso 2: Respuesta</h2>
<p class="mb-32">
  Transbank responderá con el resultado del proceso de reembolso, indicando si se ha realizado una
  Reversa, Anulación o Anulación Parcial.
</p>

<pre>
  <code class="language-json"><%= JSON.pretty_generate(@respond_data) %></code>
</pre>

<%= link_to "CONSULTAR ESTADO", webpay_deferred_status_url(token: @token), class: "tbk-button primary mb-32" %>

app/views/webpay_plus_deferred/status.html.erb
<%= render 'shared/breadcrumbs', breadcrumbs: [
  { label: 'Inicio', path: root_path },
  { label: 'Webpay Plus Diferido', path: '/webpay-plus-diferido/create' },
  { label: 'Consultar estado de transacción', path: '/webpay-plus-diferido/status' }
] %>

<h1>Webpay Plus Diferido - Consultar estado de transacción</h1>
<p class="mb-32">
    Puedes solicitar el estado de una transacción hasta 7 días después de su realización. No hay
    límite de solicitudes de este tipo durante ese período. Sin embargo, una vez pasados los 7 días, ya no podrás revisar
    su estado.
</p>

<h2 id="request">Paso 1 - Petición:</h2>
<p class="mb-32">
    Para realizar la consulta, necesitas el token de la transacción de la cual deseas obtener el estado. Utiliza
    este token para realizar una llamada al SDK.
</p>

<pre>
  <code class="language-ruby">
  @resp = @transaction.status(@token)
  </code>
</pre>

<h2 id="response">Paso 2: Respuesta</h2>
<p class="mb-32">
  Una vez que hayas creado la transacción, aquí encontrarás los datos de respuesta generados por el proceso.
</p>

<pre>
  <code class="language-json"><%= JSON.pretty_generate(@respond_data) %></code>
</pre>